# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hezhukov <hezhukov@student.42quebec.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/29 19:12:37 by hzhukov           #+#    #+#              #
#    Updated: 2023/10/16 15:29:11 by hezhukov         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRCS =	ft_atoi.c \
		ft_bzero.c \
		ft_memset.c\
		ft_isdigit.c \
		ft_isalpha.c \
		ft_isalnum.c \
		ft_isascii.c \
		# ft_isprint.c \
		# ft_strlcat.c \
		# ft_strlcpy.c \
		# ft_strlen.c \
		# ft_strncmp.c \
		# ft_tolower.c \
		# ft_toupper.c \
		# ft_strchr.c \
		# ft_strrchr.c\
		# ft_strnstr.c\
		# ft_memcpy.c\
		# ft_memmove.c\
		# ft_memchr.c\
		# ft_memcmp.c\
		# ft_calloc.c\
		# ft_strdup.c\
		# ft_substr.c\
		# ft_strjoin.c\
		# ft_strtrim.c\
		# ft_split.c\
		# ft_strmapi.c\
		# ft_striteri.c\
		# ft_putchar_fd.c\
		# ft_putstr_fd.c\
		# ft_putendl_fd.c\
		# ft_putnbr_fd.c\
		# ft_itoa.c\

OBJS = $(SRCS:.c=.o)

HEADER = libft.h

CC = gcc
CFLAGS = -Wall -Werror -Wextra

$(NAME):
	$(CC) $(CFLAGS) -c $(SRCS)
	ar rc $(NAME) $(OBJS)

all: $(NAME)

clean:
	/bin/rm -f $(OBJS)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
